### ISSUE TITLE
The website no longer in service

### ISSUE THREAD

**Issue by mldk-tech** [Gizra/Drupal8-shoov#6]
Hi @amitaibu -
It looks that  the website no longer in service
http://d8testtheuiforjs2arytcuouk.devcloud.acquia-sites.com/
![selection_010](https://cloud.githubusercontent.com/assets/5812423/18229521/2ab5a586-7285-11e6-9a80-ddd1eb467e38.png)

**Comment by amitaibu** [comment]
Please disable the test

**Comment by mldk-tech** [comment]
Done
